### ISSUE TITLE
Tuya 3.4 Device Issue (AUBESS Mini Smart Switch)

### ISSUE THREAD

**Issue by Zcorpio** [rospogrigio/localtuya-homeassistant#1229]
Hi, everyone.

I have two similar devices:
Aubess Smart Switch 1-gang
AUBESS Mini Smart Switch

First one succesfully added and work correct. The second can't obtain DPS whet I try to add it via GUI. Then I try add manualy DPS via GUI, but it does not help me. Then I tryed copy params in core.config_entries and receive next message in log:

[bf1...3ks] Connect to 192.168.1.121 failed
Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 187, in _make_connection
    self._interface = await pytuya.connect(
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 1163, in connect
    _, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1089, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1107, in _create_connection_transport
    protocol = protocol_factory()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 1164, in <lambda>
    lambda: TuyaProtocol(
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 577, in __init__
    self.cipher = AESCipher(self.local_key)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 384, in __init__
    self.cipher = Cipher(algorithms.AES(key), modes.ECB(), default_backend())
  File "/usr/local/lib/python3.10/site-packages/cryptography/hazmat/primitives/ciphers/algorithms.py", line 34, in __init__
    self.key = _verify_key_size(self, key)
  File "/usr/local/lib/python3.10/site-packages/cryptography/hazmat/primitives/ciphers/algorithms.py", line 19, in _verify_key_size
    raise ValueError(
ValueError: Invalid key size (136) for AES.

Maybe it help you fix the bug.

My system:
Home Assistant 2023.1.2
Supervisor 2023.01.dev0602
Frontend 20230104.0 - latest

**Comment by rospogrigio** [comment]
Is it a 3.4 or 3.3 device?

**Comment by rospogrigio** [comment]
You should enable pytuya debugging and post the logs you collect related to this device.
