### ISSUE TITLE
Cannot add smart string lights

### ISSUE THREAD

**Issue by Luana-98** [rospogrigio/localtuya-homeassistant#1579]
## The problem
Smart String Lights can't be added.
Product name: LED lighting chain
Brand: Quanquer
Model No: VG-P600RGB-LF5
Manufacture: VagaryLight Co., Ltd

Is it possible to add this device?

## Environment

- Localtuya version: plugin version from HACS 
- Home Assistant Core version:  
- [X] Does the device work using the Home Assistant Tuya Cloud component ? 
- [] Does the device work using the Tinytuya (https://github.com/jasonacox/tinytuya) command line tool ? 
- [] Was the device working with earlier versions of localtuya ? Which one? 
- [X] Are you using the Tuya/SmartLife App in parallel ? 

## Steps to reproduce

1.
2. 
3.

## Provide Home Assistant traceback/logs

```
put your log output between these markers
```

**Comment by Node815** [comment]
Same here, Glad to see this, as the DP dump was not provided, here's mine:

```{
  "result": {
    "properties": [
      {
        "code": "switch_led",
        "custom_name": "",
        "dp_id": 20,
        "time": 1702426523399,
        "value": true
      },
      {
        "code": "work_mode",
        "custom_name": "",
        "dp_id": 21,
        "time": 1702426486106,
        "value": "colour"
      },
      {
        "code": "bright_value",
        "custom_name": "",
        "dp_id": 22,
        "time": 1702424947362,
        "value": 10
      },
      {
        "code": "colour_data",
        "custom_name": "",
        "dp_id": 24,
        "time": 1702426527998,
        "value": "0000000003e8"
      },
      {
        "code": "music_data",
        "custom_name": "",
        "dp_id": 27,
        "time": 1702424947362,
        "value": ""
      },
      {
        "code": "Slowflash",
        "custom_name": "",
        "dp_id": 102,
        "time": 1702426486106,
        "value": "ffff3207ff000000ff00ffff000000ffff00ff00ffffffffff"
      },
      {
        "code": "Jump",
        "custom_name": "",
        "dp_id": 103,
        "time": 1702426486106,
        "value": "ffff3207ff000000ff00ffff000000ffff00ff00ffffffffff"
      },
      {
        "code": "FLASH",
        "custom_name": "",
        "dp_id": 104,
        "time": 1702426486106,
        "value": "ffff3207ff000000ff00ffff000000ffff00ff00ffffffffff"
      },
      {
        "code": "STROBE",
        "custom_name": "",
        "dp_id": 105,
        "time": 1702426486106,
        "value": "ffff3207ff000000ff00ffff000000ffff00ff00ffffffffff"
      },
      {
        "code": "ASYNFADE",
        "custom_name": "",
        "dp_id": 106,
        "time": 1702426486106,
        "value": "00006400000000000000000000000000000000000000"
      },
      {
        "code": "ASYNJUMP",
        "custom_name": "",
        "dp_id": 107,
        "time": 1702426486106,
        "value": "00003200000000000000000000000000000000000000"
      },
      {
        "code": "Auto",
        "custom_name": "",
        "dp_id": 108,
        "time": 1702426486106,
        "value": "00320000"
      },
      {
        "code": "INWAVES",
        "custom_name": "",
        "dp_id": 109,
        "time": 1702426486106,
        "value": "00320700ff0000ffff0000ff0000ffff0000ffff00ffffffff"
      },
      {
        "code": "doubleStrobe",
        "custom_name": "",
        "dp_id": 110,
        "time": 1702426486106,
        "value": "00320601ff0000ffff0000ff0000ffff0000ffff00ffffffff"
      },
      {
        "code": "TWINKLE",
        "custom_name": "",
        "dp_id": 111,
        "time": 1702426486106,
        "value": "00320700ff0000ffff0000ff0000ffff0000ffff00ffffffff"
      },
      {
        "code": "SETAT",
        "custom_name": "",
        "dp_id": 112,
        "time": 1702426486106,
        "value": "00000600ff000000ff000000ffffff0000ffffff00ff"
      }
    ]
  },
  "success": true,
  "t": 1702426550109,
  "tid": "XXXXXXXXXXXXxx" (I don't think that's needed) 
  }```

**Comment by Node815** [comment]
To start, I got it to work to turn on/off, but no color modes yet:
![image](https://github.com/rospogrigio/localtuya/assets/20736534/261d598e-a760-4d9c-97da-86b1a5117195)
And So far, this is what I have:
![image](https://github.com/rospogrigio/localtuya/assets/20736534/b94fd953-bc36-40b0-b136-308a2fa3b589)

It will at least toggle and respond to the power toggle from Home Assistant.  I've tried the other DP's with no success so far.  Color I think needs 0000000003e8 which is not an option to match DP 24:
![image](https://github.com/rospogrigio/localtuya/assets/20736534/cd85b966-6981-47cd-a238-99e158295f9f)

**Comment by Node815** [comment]
For now, just install the Tuya device (from Home Assistant), it requires your Client ID and Secret from Tuya Developers, but I got the lights FULLY integrated with it no issues.   I figure having it tied to them for the rest of the season is good enough until this is hopefully figured out.

**Comment by Luana-98** [comment]
I am following your guide but when I set Manual DPs and click on SEND I get this log error

```
This error come out from a personalized integration

Logger: custom_components.localtuya.config_flow
Source: custom_components/localtuya/config_flow.py:595
Integration: LocalTuya (documentation, issues)
First occurred: 18:51:25 (4 occurrences)
Last logged: 19:06:30

Unexpected exception: [Errno 113] Connect call failed ('192.168.1.11', 6668)
Traceback (most recent call last):
  File "/config/custom_components/localtuya/config_flow.py", line 595, in async_step_configure_device
    self.dps_strings = await validate_input(self.hass, user_input)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/config_flow.py", line 242, in validate_input
    interface = await pytuya.connect(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 1182, in connect
    _, protocol = await loop.create_connection(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1085, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 628, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 668, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.1.11', 6668)

```
