### ISSUE TITLE
Tuya Ceiling Fan Light Controller

### ISSUE THREAD

**Issue by AnthonyD42** [rospogrigio/localtuya-homeassistant#59]
Hey Guys, 
I see that you are working to make the tuya stuff local and wanted to throw some data your way regarding the QIACHIP Ceiling Fan Remote Control Kit, WI-FI Smart Universal Ceiling Fan with Amazon Alexa 
by QIACHIP Store 
Learn more: https://www.amazon.com/dp/B07RYD632T/ref=cm_sw_em_r_mt_dp_5CNCFbHYWT4JV 

I was able to pair this thing to the Tuya App on my iPhone and was able to find it get it paired on iot.tuya.com.
Not sure what you need to get it to work locally.  I was able to pair the controller as a switch and it does turn the fan on and off.  However, I was not able to add the device as a fan, so I have no control over the speed at this time.

So I pulled what I could from iot.tuya.com.
Standard Function Set
Code | Type | Values
-- | -- | --
switch | Boolean | {true,false}
fan_speed | Enum | {"range":["1","2","3"]}
countdown | Enum | {"range":["0","1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16"]}
light | Boolean | {true,false}
fan_beep | Boolean | {true,false}

Standard State Set
Code | Type | Values
-- | -- | --
switch | Boolean | {true,false}
fan_speed | Enum | {"range":["1","2","3"]}
countdown | Enum | {"range":["0","1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16"]}
light | Boolean | {true,false}
fan_beep | Boolean | {true,false}

**Comment by postlund** [comment]
Have not started to look into this yet, but should definitely be possible to fix. Great summary of the datapoints 👍

**Comment by postlund** [comment]
Ok, let's have a look at this now. When you tried the last time, which version of this component did you use? I would suggest that you try the latest, 2.0.0, and make a new attempt as a lot has changed. It should be possible to turn on/off and change fan speed. DPS for fan speeds are however hardcoded right now, so if they are different we need to add support for changing those.

**Comment by AnthonyD42** [comment]
Okay, I was able to add the fan via the HACS integration.  However, I am stumped on what ID to select.  Forgive me here, but, I am not familiar with what the values translates to.  Attached is a screen shot of the values I get when I select Fan for the device.  How do I know which to select? Same thing with the Light.  I get a slider for brightness, and the light seem to only toggle the fan on and off.
![image](https://user-images.githubusercontent.com/21263818/95143970-13b59980-073d-11eb-8868-a5913a83bd84.png)

**Comment by postlund** [comment]
From an outside perspective, the state of a Tuya device is represented by a set of datapoints (that's what we call DPS). A datapoint is simply a number/index with an assigned value. The datapoints are what you see in the list with the current value for each datapoint. There are a few standard datapoints defined by Tuya, but each vendor can define their own and even use other datapoints than the ones defined. For this reason we can't provide simple templates for devices, because which datapoints to use depends on the vendor (and can probably be different depending on product as well).

As I said, there are a few datapoints that are more commonly used than others. But you kinda have to reverse engineer what the datapoints mean. The field `ID` corresponds to the datapoint used to turn on or off the devices, which is usually defined by a boolean. So a datapoint with True/False as value is likely what you are looking for. Normally this is also datapoint 1 (or 2 if you have a double gang wall socket for instance).

**Comment by AnthonyD42** [comment]
Understood, I will do some more play around with it some more and see if I can home in on the correct settings.  Thanks for the feedback and good work!

**Comment by AnthonyD42** [comment]
Sorry for getting back so late.  Here's what I have discovered regarding the ID.
Using the Fan option with ID3 gives me the speed options; however, there are some caveats:
1) Changing the value to Low, Medium, High returns the module to the last state set by the tuya smart app or the remote.  For example, if I set the fan speed to medium with the remote or the app, and then I try to change the value in HA, the speed does not change.  However, I can turn the fan off, by changing the speed to off or toggling Fan Switch ID1.
Not sure this this info from the log is of any use regarding changing the speed value from off to low:


2020-10-09 19:28:02 DEBUG (SyncWorker_6) [custom_components.localtuya.common] running def status(self) from TuyaDevice
2020-10-09 19:28:03 DEBUG (SyncWorker_6) [custom_components.localtuya.common] running def __get_status from TuyaDevice
2020-10-09 19:28:03 DEBUG (SyncWorker_6) [custom_components.localtuya.pytuya] Sending command status (device type: type_0d)
2020-10-09 19:28:03 DEBUG (SyncWorker_6) [custom_components.localtuya.pytuya] paylod=b'{"devId":"6cb6#########rt0","uid":"#########","t":"1602289683","dps":{"1":null,"3":null,"9":null}}'
2020-10-09 19:28:03 DEBUG (SyncWorker_6) [custom_components.localtuya.pytuya] decode payload=b'3.3\x00\x00\x00\x00\x00\x00\n\xa1\x00\x00\x00\x01OS\xf3L[^S\xbe\xb7y\xea\xca\xe3-\xcc\xa9*4\xe5\x8e\x06\xe1\x19|T"\x83?\xb3\xdd\xc0V%p\xfe\xb2\x8d`\x04\x0e\xff\xeb<S\x1d\x02\x91\\\r?\xf4\xe2\xe6U\x8b\x13\xa6\xe2\x19\x15aq-\xa1'
2020-10-09 19:28:03 DEBUG (SyncWorker_6) [custom_components.localtuya.pytuya] decrypted result='{"dps":{"1":true,"3":"2","9":false},"t":1602289682}'
2020-10-09 19:28:03 ERROR (SyncWorker_22) [homeassistant.util.logging] Exception in _update_handler when dispatching 'localtuya_########': ({'dps': {'1': True, '3': '2', '9': False}, 't': 1602289682},)
Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 198, in _update_handler
    self.status_updated()
  File "/config/custom_components/localtuya/fan.py", line 104, in status_updated
    elif self._status["dps"]["2"] == "1":
KeyError: '2'


2) It's a ceiling fan, and the Oscillate switch is not supported.  I get the following error in the log:
"    self.status_updated()
  File "/config/custom_components/localtuya/fan.py", line 110, in status_updated
    self._oscillating = self._status["dps"]["8"]
KeyError: '8'"

As for the Light, Fan Light Switch ID 9 seems to work fine, however, I have to set this up as a switch vs. using the Light.  The module doesn't recognize the dimmer feature that the light option has.

  

![image](https://user-images.githubusercontent.com/21263818/95640691-85eeec80-0a63-11eb-8bbd-1beec3c6c14a.png)

**Comment by postlund** [comment]
Some work to improve the state of `fan` is being done in #77, so might be worth monitoring that. Support for manually specifying datapoints is an important thing that is missing.

**Comment by AnthonyD42** [comment]
Wow! 3.0 is so much more responsive.  I will definitely monitor #77, thanks again!

**Comment by postlund** [comment]
@AnthonyD42 The stuff from #77 is merged now, so things should probably work better. But we don't support everything mentioned in the function set you posted. @ThomasADavis Since you are an expert in then fan department now, is this something you feel that would want to/have time to implement?

**Comment by sEdsKi** [comment]
Hi All

I'm stoked that I have been able 3-speed fan switch integrated however, the same switch panel has a light
Currently, I'm able to use the oscillate toggle to turn the light on and off.
How can I get this to work in a card?

<img width="348" alt="image" src="https://user-images.githubusercontent.com/98076159/151293478-6ac87c3a-ab59-43ec-8492-ee8bb89c985e.png">
