### ISSUE TITLE
local tuya not connecting in HA

### ISSUE THREAD

**Issue by k-rock** [rospogrigio/localtuya-homeassistant#592]
I am seeing this error in my local tuya & haven't changed any configs.

  OS Version:               Home Assistant OS 6.5
  Home Assistant Core:      2021.10.3

This error originated from a custom integration.

Logger: custom_components.localtuya.common
Source: custom_components/localtuya/pytuya/__init__.py:196
Integration: LocalTuya (documentation, issues)
First occurred: 9:42:02 AM (2268 occurrences)
Last logged: 3:15:05 PM

[eb3...z92] Connect to 192.168.86.249 failed
Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 149, in _make_connection
    status = await self._interface.status()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 472, in status
    status = await self.exchange(STATUS)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 457, in exchange
    payload = self._decode_payload(msg.payload)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 544, in _decode_payload
    payload = self.cipher.decrypt(payload, False)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 196, in decrypt
    return self._unpad(decryptor.update(enc) + decryptor.finalize()).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfb in position 0: invalid start byte

**Comment by johnahyland** [comment]
Same issue with a power strip with 4 switches and USB, not connecting to it after upgrading to Core 2021.10.5  but works fine when I restore backup to Core 2021.9.7.

A Tuya Blind/Cover does work ok with Core 2021.10.5.

**Comment by reidkersey** [comment]
Same, with the same OS and core

**Comment by johnahyland** [comment]
I had the same issue after upgrading from 2021.9.7 to 2021.10.4 with one of my Tuya switches but a Tuya Blind/Cover worked fine. I was also unable to control the power strip switch from HA.

In integrations, Local Tuya, I selected the device which was not working, selected Configure and on the Protocol Version I changed it from 3.3 to 3.1 and Submitted everything again. I possibly restarted HA again and now I'm not getting the error anymore and can also control the 4 switches on the power strip again from HA!

**Comment by johnahyland** [comment]
Update - I just updated to 2021.10.5 and lost control to the Tuya Switch again from HA. In LocalTuya, just selected the device which was not working, Configure and submitted all details again without restarting HA and can now control the switch again from HA!

**Comment by shtrom** [comment]
Sounds similar to #424.
