### ISSUE TITLE
HA error log filling up with errors for unplugged devices

### ISSUE THREAD

**Issue by adorobis** [rospogrigio/localtuya-homeassistant#607]
## The problem

Local tuya integration fills in error log with multiple error messages for devices that are disconnected from power outled. Better error handling is required as the log grows significantly (a few MB after a day)

## Environment

- Localtuya version:  v3.2.3
- Last working localtuya version (if known and relevant): not sure
- Home Assistant Core version:   2021.10.6
- [] Are you using the Home Assistant Tuya Cloud component ? 
- [] Are you using the Tuya App in parallel ? 

## Steps to reproduce

1. Configure smart plug as per guideline (example provided below)
2. Disconnect smart plug from power outlet
3. Restart HA

## Configuration `configuration.yaml` or `config_flow`

```
- host: 10.144.1.133
  device_id: xxxx
  local_key: yyyy
  friendly_name: Tuya Plug 3
  protocol_version: "3.3"
  entities:
    - platform: switch
      friendly_name: Tuya Plug 3
      id: 1
      current: 18 # Optional
      current_consumption: 19 # Optional
      voltage: 20 # Optional
```

## Provide Home Assistant taceback/logs

```
2021-10-26 12:18:41 ERROR (MainThread) [custom_components.localtuya.common] [586...0fe] Connect to 10.144.1.133 failed
Traceback (most recent call last):
  File "/home/homeassistant/homeassistant/custom_components/localtuya/common.py", line 139, in _make_connection
    self._interface = await pytuya.connect(
  File "/home/homeassistant/homeassistant/custom_components/localtuya/pytuya/__init__.py", line 637, in connect
    _, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 496, in sock_connect
    return await fut
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 528, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 60] Connect call failed ('10.144.1.133', 6668)
```

**Comment by tankdeer** [comment]
I have noticed this same behavior

**Comment by skallberg** [comment]
I also have this issue

**Comment by maurizioandreotti60** [comment]
I noticed the same behavior. I would like to avoid those error message  or at least a way to control whiche error message should be produced.

**Comment by 1RandomDev** [comment]
Just add this filter to the logger in your configuration.yml
```yaml
logger:
  default: error
  filters:
    custom_components.localtuya.common:
      - "Connect to .* failed"
```

**Comment by tankdeer** [comment]
> Just add this filter to the logger in your configuration.yml
> 
> ```yaml
> logger:
>   default: error
>   filters:
>     custom_components.localtuya.common:
>       - "Connect to .* failed"
> ```

This is an effective band-aide, so thanks for that. But I think we all realize it is just that - a band-aide.
