### ISSUE TITLE
Problems adding more than one entity at the same device

### ISSUE THREAD

**Issue by PaoloC87** [rospogrigio/localtuya-homeassistant#798]
Hi
after the last update at 2022.4.1 I also updated Localtuya at the last version.
I have two devices with more than one entites: Curtain up/down/stop and light.
Curtains side no problem, but the entities light reamin unaviable for both devices.

log  error:ù

2022-04-12 12:33:32 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 519, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 573, in _async_write_ha_state
    attr.update(self.extra_state_attributes or {})
  File "/config/custom_components/localtuya/switch.py", line 58, in extra_state_attributes
    self.dps(self._config[CONF_CURRENT_CONSUMPTION]) / 10
TypeError: unsupported operand type(s) for /: 'str' and 'int'

I'm using LocalTuya version 3.5.0

**Comment by creeve4** [comment]
Also seeing this in my logs.

```
Error doing job: Task exception was never retrieved

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 519, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 573, in _async_write_ha_state
    attr.update(self.extra_state_attributes or {})
  File "/config/custom_components/localtuya/switch.py", line 58, in extra_state_attributes
    self.dps(self._config[CONF_CURRENT_CONSUMPTION]) / 10
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
```
