### ISSUE TITLE
v4 errors in log

### ISSUE THREAD

**Issue by regevbr** [rospogrigio/localtuya-homeassistant#857]
## The problem
After upgrading to v4, I get 15 occurrences in the log:
```txt
Logger: homeassistant.config_entries
Source: helpers/entity_component.py:157
First occurred: 13:26:53 (15 occurrences)
Last logged: 13:26:53

Error setting up entry localtuya for light
Error setting up entry localtuya for cover
Error setting up entry localtuya for switch
Error setting up entry localtuya for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 597, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 157, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
```

Everything seems to be working fine so I'm not sure what those errors mean or affect

## Environment
- Localtuya version: 4.0.0
- Last working localtuya version (if known and relevant): 3.5.0
- Home Assistant Core version: 2022.6.5
- [x] Are you using the Home Assistant Tuya Cloud component?
- [x] Are you using the Tuya App in parallel?

**Comment by Grunn95** [comment]
Same here

Logger: homeassistant.config_entries
Source: helpers/entity_component.py:157
First occurred: 09:24:52 (11 occurrences)
Last logged: 09:24:52

Error setting up entry localtuya for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 597, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 157, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!

**Comment by Duke-Box** [comment]
Same error in my logs too after update to LocalTuya v4.0

**Comment by Senbei123** [comment]
Just to get an update, here is mine:

Logger: homeassistant.config_entries
Source: helpers/entity_component.py:157
First occurred: 18. Juni 2022 um 23:45:32 (3 occurrences)
Last logged: 18. Juni 2022 um 23:45:32

Error setting up entry localtuya for switch
Error setting up entry localtuya for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/switch/__init__.py", line 81, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 157, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!

**Comment by abonforti** [comment]
Same here:
Home Assistant supervised on Debian 11 proxmox emulated
Fresh install, localtuya v4.0.0 and HA core-2022.6.6:

`2022-06-21 17:24:16 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry localtuya for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/switch/__init__.py", line 81, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 157, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2022-06-21 17:24:16 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry localtuya for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/switch/__init__.py", line 81, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 157, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2022-06-21 17:24:16 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry localtuya for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/switch/__init__.py", line 81, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 157, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!`

**Comment by rospogrigio** [comment]
OK, the mentioned commit is already merged in master, will release it soon....

**Comment by rospogrigio** [comment]
> Hi, any update about the release?

Ooops, done right now! 😉
